# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bundle-audit'
gem 'loofah'
gem 'puma'
gem 'rack'
gem 'rackup'
gem 'rspec'
gem 'sinatra'

# Gemfile
group :development, :test do
  gem 'rubocop', require: false
end
